acceso/urls.py
from django.urls import path
from .views import LoginView, login, logout

app_name = 'acceso'

urlpatterns = [
    path('', LoginView.as_view(), name='acceso' ),
    path('login/', login, name='login' ),
    path('logout/', logout, name='logout' ),
    
    
]

core/urls.py
from django.urls import path
from core.views.libros import LibrosView, LibrosDetailView
from .views.index import index

urlpatterns = [
    path('', index, name="index"),

   
    path('libros/', LibrosView.as_view(), name='libros' ),
    path('libros/<int:id>/', LibrosDetailView.as_view(), name='libros_editar' ),
]

proyecto_base/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from decorator_include import decorator_include
from acceso.utils.decoradores import login_requerido

urlpatterns = [
    path('',  decorator_include(login_requerido,include('core.urls'))),
    path('acceso/', include('acceso.urls')),
    path('admin/', admin.site.urls),
]

acceso/models.py
from django.db import models


# Create your models here.
class Usuario(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    username = models.CharField(max_length=20, unique=True, verbose_name="Nombre de Usuario")
    email = models.EmailField(max_length=200, unique=True)
    password = models.CharField(max_length=72)
    description = models.TextField(default='')
    birthday = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"
        

    

acceso/forms.py
from datetime import date

from django import forms

from acceso.models import Usuario

CIERTA_EDAD = 13

def calculate_age(born):
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))


class UsuarioForm(forms.ModelForm):

    confirmar_password = forms.CharField(label="Confirmar Contraseña", widget=forms.PasswordInput(attrs={'class':'form-control'}))


    def clean_birthday(self):
        birthday = self.cleaned_data['birthday']
        edad = calculate_age(birthday)

        if birthday > date.today():
            raise forms.ValidationError(
                    f"solo fechas en pasado."
                )

        if edad < CIERTA_EDAD:
            raise forms.ValidationError(
                    f"La edad es menor a {CIERTA_EDAD}, porque tiene {edad} años."
                )
        return birthday

    def clean_nombre(self):
        nombre = self.cleaned_data['nombre']
        if nombre == "PANCHO": 
            self.add_error('nombre', "El nombre es PANCHO")
        return nombre

    def clean(self):
        cleaned_data = super().clean()
        print(cleaned_data)

        if cleaned_data.get('password') != cleaned_data.get('confirmar_password'):
            raise forms.ValidationError(
                    "Las contraseñas no coinciden"
                )

    class Meta:
        model = Usuario
        fields  = ['nombre','apellido','username','email','birthday','password']

        labels = {
            'nombre':'Nombre: ',
            'apellido':'Apellido: ',
            'username':'Nombre Usuario: ',
            'email':'Correo: ',
            'birthday': 'Cumpleaños:',
            'password':'Contraseña: ',
            'description': 'Descripción'
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'type':'email'}),
            'birthday': forms.DateInput(attrs={'class': 'form-control', 'type':'date', 'max':date.today().strftime('%Y-%m-%d')}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

acceso/views.py
from django import forms
from django.shortcuts import redirect, render
from django.db.models import Q
from django.urls import reverse
from django.views import View
from django.contrib import messages
from acceso.forms import UsuarioForm
from acceso.models import Usuario
import bcrypt
# Create your views here.

class LoginForm(forms.Form):
    username = forms.CharField(
                    label='Usuario', 
                    max_length=50, 
                    required=True, 
                    widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Usuario o Email'})
                )

    password = forms.CharField(
                    label='Contraseña', 
                    required=True, 
                    widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'Contraseña'})
                )



class LoginView(View):
    
    def get(self, request):

        if 'usuario' in request.session:
            messages.error(request, 'YA ESTAS LOGEADO. Si quieres salir, CLICK EN SALIR!!')
            return redirect('/')

        contexto = {
            'formRegister': UsuarioForm(),
            'formLogin': LoginForm()
        }

        return render(request, 'acceso/login.html', contexto)

    def post(self, request):
        print(request.POST)

        form = UsuarioForm(request.POST)

        if form.is_valid():
            
            usuario = form.save(commit=False)
            usuario.password = bcrypt.hashpw(usuario.password.encode(), bcrypt.gensalt()).decode()
            usuario.save()
            
            messages.success(request, 'Usuario creado correctamente')
            return redirect(reverse('acceso:acceso'))
        else:

            contexto = {
                'formRegister': form,
                'formLogin': LoginForm()
            }

            messages.error(request, 'Con errores, solucionar.')
            return render(request, 'acceso/login.html', contexto) 


def login(request):

    if request.method == 'POST':

        form = LoginForm(request.POST)

        if form.is_valid():
            
            user = Usuario.objects.filter(Q(username=form.cleaned_data['username'])| Q(email=form.cleaned_data['username'])).first()
            if user:
                form_password = form.cleaned_data['password']
                if bcrypt.checkpw(form_password.encode(), user.password.encode()):
                    
                    request.session['usuario'] = { 'nombre' : user.nombre, 'email' : user.email, 'username' : user.username, 'id': user.id }
                    return redirect('/')
                else:
                    messages.error(request, '1Contraseña o Email o Nombre de Usuario INCORRECTO')
            else:
                messages.error(request, '2Contraseña o Email o Nombre de Usuario INCORRECTO')

            return redirect(reverse('acceso:acceso'))
        else:
            contexto = {
                'formRegister': UsuarioForm(),
                'formLogin': form
            }
            return render(request, 'acceso/login.html', contexto) 

def logout(request):

    if 'usuario' in request.session:
        messages.success(request, 'SALISTE')
        del request.session['usuario']
    else:
        messages.error(request, 'Tu no estas logeado.')

    return redirect(reverse('acceso:acceso'))

acceso/templates/acceso/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJANGO POST - {% block titulo %}{% endblock %}</title>
    {% load static %}	
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">  
    <link rel="stylesheet" href="{% static 'css/toastr.css' %}">  
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" /><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    {% block estilos %}
    <style>
        h3{
            text-align: center;
            margin-top: 5px;
        }
    </style>

    
    {% endblock %}
</head>
<body>
  
    {% block contenido %}{% endblock %}


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>

    <script>


        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }

        {% if messages %}
        {% for message in messages %}
            toastr.{{ message.tags }}('{{ message }}', 'MENSAJE!!!!');
        {% endfor %}
        {% endif %}

    </script>

    
    {% block scripts %}{% endblock %}

</body>
</html>

acceso/templates/acceso/login.html
{% extends "acceso/base.html"%}

{% block titulo %}Login y Register{% endblock %}

{% block contenido %}

<div class="container mt-5 bg-secondary rounded">
    
    <div class="row">
        <div class="col-md-6">
            <h3><i class="fa fa-user-circle" aria-hidden="true"></i>Register</h3>
            <hr>

            <form action="" method="post">
            
                {% csrf_token %}
                {{ formRegister.non_field_errors }}

                {% for field in formRegister %}
                <div class="mb-3 row">


                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>

                    {% if field.errors %}

                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>

                    {% endif %}

                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                <button class="btn btn-primary offset-3" type="submit">Enviar</button>
            </form>
        </div>
        <div class="col-md-6">
            <h3><i class="fa fa-user-circle-o" aria-hidden="true"></i>Login</h3>
            <hr>

            <form action="{% url 'acceso:login' %}" method="post">
            
                {% csrf_token %}
                {{ formLogin.non_field_errors }}

                {% for field in formLogin %}
                <div class="mb-3 row">


                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>

                    {% if field.errors %}

                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>

                    {% endif %}

                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                <button class="btn btn-primary offset-3" type="submit">Enviar</button>
            </form>
        </div>
    </div>

</div>


{% endblock %}