acceso/urls.py
from django.urls import path
from .views import LoginView, login, logout

app_name = 'acceso'

urlpatterns = [
    path('', LoginView.as_view(), name='acceso' ),
    path('login/', login, name='login' ),
    path('logout/', logout, name='logout' ),
    
    
]

core/urls.py
from django.urls import path
from core.views.libros import LibrosView, LibrosDetailView
from .views.index import index

urlpatterns = [
    path('', index, name="index"),

   
    path('libros/', LibrosView.as_view(), name='libros' ),
    path('libros/<int:id>/', LibrosDetailView.as_view(), name='libros_editar' ),
]

proyecto_base/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from decorator_include import decorator_include
from acceso.utils.decoradores import login_requerido

urlpatterns = [
    path('',  decorator_include(login_requerido,include('core.urls'))),
    path('acceso/', include('acceso.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models
from acceso.models import Usuario

class Libro(models.Model):
 
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    usuarios = models.ForeignKey(Usuario, related_name="libros", on_delete=models.CASCADE)
    # favorito = models.ManyToManyField(Usuario, related_name="favoritos")


    def __str__(self):
        return self.titulo

core/forms.py
from django import forms
from core.models import Libro

class LibroForm(forms.ModelForm):

    class Meta:
        model = Libro
        fields = ['titulo', 'descripcion']

        labels = {
            'titulo': 'Titulo',
            'descripcion': 'Descripcion',
            
        }

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
            
        }

core/views.py
from django.shortcuts import render, HttpResponse

from acceso.utils.decoradores import login_requerido

def index(request):
    return render(request, 'core/index.html')

core/views/index.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')

core/views/libros.py
from django.views import View
from django.contrib import messages
from django.shortcuts import redirect, render
from django.urls import reverse
from acceso.models import Usuario
from core.models import Libro
from core.forms import LibroForm

class LibrosView(View):
    
    def get(self, request):
        contexto = {
            'form': LibroForm(), 
            'libros' : Libro.objects.all(),
        }
        return render(request, 'core/libros.html', contexto)

    def post(self, request):
        print(request.POST)
        form = LibroForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Libro Creado')
            return redirect(reverse('libros'))
        else:
            contexto = {
                'form': form, 
                'libros' : Libro.objects.all(),
            }
            messages.error(request, 'Con errores, solucionar.')
            return render(request, 'core/libros.html', contexto) 

class LibrosDetailView(View):
    
    def get(self, request, id):
        usuario = Libro.objects.get(id=id)
        contexto = {
            'form': LibroForm(instance=usuario), 
            'libros' : Libro.objects.all(),
        }
        return render(request, 'core/libros.html', contexto)

    def post(self, request, id):
        
        usuario = Libro.objects.get(id=id)

        form = LibroForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            messages.success(request, 'Libro Editado')
            return redirect(reverse('libros'))
        else:

            contexto = {
                'form': form, 
                'libros' : Libro.objects.all(),
            }

            messages.error(request, 'Con errores, solucionar.')
            return render(request, 'core/libros.html', contexto) 

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJANGO POST - {% block titulo %}{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/toastr.css' %}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer"
    /> {% block estilos %}{% endblock %}
</head>

<body>

    {% include 'core/menu.html' %} 
    
    {% block contenido %}{% endblock %}


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/toastr.min.js' %}"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>

    <script>


        toastr.options = {
            "closeButton": true,
            "progressBar": true
        }

        {% if messages %}
        {% for message in messages %}
            toastr.{{ message.tags }}('{{ message }}', 'MENSAJE!!!!');
        {% endfor %}
        {% endif %}

    </script>

    
    {% block scripts %}{% endblock %}

</body>
</html>

core/templates/core/index.html
{% extends "core/base.html"%}

{% block titulo %}BIENVENIDA{% endblock %}

{% block estilos %}

<style>

    h1{
        text-align: center;
        font-size: 50px;
        margin-top: 100px;
    }
</style>

{% endblock %}

{% block contenido %}

<div class="container mt-5">
    <h1>Bienvenidos a Mi Aplicación</h1>
    <hr>
</div>


{% endblock %}

core/templates/core/libros.html
{% extends "core/base.html"%}

{% block titulo %}Libros{% endblock %}

{% block estilos %}

<style>

    h1{
        text-align: center;
        font-size: 50px;
        margin-top: 100px;
    }
</style>

{% endblock %}

{% block contenido %}

<div class="container mt-5">
    <h1>Libros</h1>
    <hr>

    <div class="row">
        <ul>
            {% for libro in libros %}
                <li>{{libro}} -<a href="{% url 'libros_editar' id=libro.id %}">EDITAR</a></li>
                <ul>
                    {% for usuario in libro.usuarios.all %}
                        <li>{{usuario}} - <a href="{% url 'libros_editar' id=usuario.id %}">EDITAR</a></li>
                    {% endfor %}
                </ul>
            {% endfor %}
        </ul>
        <div class="col-6">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="mb-3 row">


                    <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                    </div>

                    {% if field.errors %}

                    <div class="alert alert-danger mt-2" role="alert">
                        {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    </div>

                    {% endif %}

                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
                {% endfor %}

                <button class="btn btn-primary offset-3" type="submit">Enviar</button>
            </form>
        </div>
    </div>


</div>


{% endblock %}

core/templates/core/menu.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}"><i class="fa fa-home" aria-hidden="true"></i></i></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'libros' %}">Agregar Libros</a>
            </li>



          </ul>
          <div class="d-flex">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                      <span class="nav-link active text-info">Bienvenido, <b>{{request.session.usuario.nombre}}</b></span>
                  </li>
              </ul>
              <a href="{% url 'acceso:logout' %}" class="btn btn-outline-danger">SALIR</a>
          </div>
      </div>
  </div>
</nav>